version: "3.9"
services:
  postgres:
    image: registry:2
    container_name: registry
    hostname: registry
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/registry
    ports:
      - "${PORT:-5000}:5000"
